### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by tomkuba**
1. I like the list of VMs ordered by name. This is the same piece of code as used on vRA web.
2. Networking example now returns networking data

### CODE REVIEW

**Comment by chelnak** [comment]
Will check and merge shortly! Thanks!

**Comment by tomkuba** [comment]
I noticed that (according to documentation) the variable used in getResourceNetworking example should be "networking" instead of "resource"

**Comment by chelnak** [comment]
You are right. 

I tend to use networking or resourceNetworking  as the variable.

So long as its descriptive of what you are trying to do its all good.

I've got a feeling that I must have over written the getResourceNetworking file at some point because it used to be correct! :-)

I think, before I write up the reservation docs, I'll scan over the catalog scripts and docs to make sure everything is consistent.

**Comment by chelnak** [comment]
Tested and merged :-)

**Pull request merged**
